### ISSUE TITLE
`generate_lambda_session_name` can return a session name >64 chars

### ISSUE THREAD

**Issue by lorengordon** [benkehoe/aws-assume-role-lib#2]
Just ran into this issue... if the function name is sufficiently long, the session name returned by `generate_lambda_session_name` will fail...

```
An error occurred (ValidationError) when calling the AssumeRole operation: 1 validation error detected: Value 'new-account-trust-policy-nnnnnnnnnnn.mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm' at 'roleSessionName' failed to satisfy constraint: Member must have length less than or equal to 64
```

**Comment by benkehoe** [comment]
Do you think it should be the function name or the identifier that should be truncated? My gut says identifier, there's more uniqueness in it than the function name

**Comment by lorengordon** [comment]
I think I agree... Use only the first 64 chars and whatever snippet of the identifier makes it, _hopefully_ will be unique enough to trace it down...

**Comment by benkehoe** [comment]
Try version 1.7. I tried to make it smart, so the format is always kept, rather than just truncating it plainly. See the [readme](https://github.com/benkehoe/aws-assume-role-lib#role-session-names-for-lambda-functions).

**Comment by lorengordon** [comment]
Works like a champ, thanks!
